# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: session.handler.native_file
        cookie_secure: auto
        cookie_samesite: lax

    # Uncomment these lines if you want to enable ESI and fragments
    # esi: true
    # fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
