# config/services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Service\Cart:
    arguments:
      $requestStack: '@request_stack'
      $produitRepository: '@App\Repository\ProduitRepository'

  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']
    public: true

  App\Repository\:
    resource: '../src/Repository'
    public: false

  App\Security\Authenticator:
    autowire: true
    autoconfigure: true

  App\Security\EmailVerifier:
    autowire: true
    autoconfigure: true

  App\Controller\RegistrationController:
    arguments:
      $emailVerifier: '@App\Security\EmailVerifier'